version: '3'

services:
  node:
    build: ./.docker
    volumes:
      - .:/testing-locations
    working_dir: /testing-locations
    command: tail -f /dev/null
    # To do Use Traefik to avoid port conflicts
    ports:
      - 3000:3000